# Generated by Django 5.1.11 on 2025-06-30 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "rcabinet_url",
                    models.URLField(blank=True, verbose_name="R-Cabinet文件URL"),
                ),
                (
                    "rcabinet_file_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="R-Cabinet文件ID",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(verbose_name="文件大小(字节)"),
                ),
                (
                    "content_type",
                    models.CharField(max_length=100, verbose_name="文件类型"),
                ),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("pending", "等待上传"),
                            ("completed", "上传完成"),
                            ("failed", "上传失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="上传状态",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "db_table": "media_files",
                "indexes": [
                    models.Index(
                        fields=["user", "upload_status"],
                        name="media_files_user_id_d3bdb0_idx",
                    )
                ],
            },
        ),
    ]
