# Generated by Django 5.1.11 on 2025-07-01 08:26

import django.db.models.deletion
import pages.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="页面模板的唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="用户设定的页面名称", max_length=255),
                ),
                (
                    "content",
                    models.JSONField(
                        default=list,
                        help_text="存储PageModule数组的JSON字段",
                        validators=[pages.models.validate_json_content],
                    ),
                ),
                (
                    "target_area",
                    models.CharField(help_text="关联乐天目标区域", max_length=100),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="最后更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="页面模板的所有者",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "页面模板",
                "verbose_name_plural": "页面模板",
                "db_table": "pages_pagetemplate",
                "ordering": ["-updated_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-updated_at"],
                        name="pages_paget_owner_i_54a334_idx",
                    ),
                    models.Index(
                        fields=["target_area"], name="pages_paget_target__2926e2_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="pages_paget_created_d84eec_idx"
                    ),
                ],
            },
        ),
    ]
