# Generated by Django 5.1.11 on 2025-10-11 02:51

import django.db.models.deletion
import pages.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0002_shopconfiguration_api_license_expiry_date"),
        ("pages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetemplate",
            name="device_type",
            field=models.CharField(
                choices=[("pc", "PC端"), ("mobile", "移动端")],
                default="pc",
                help_text="设备类型",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pagetemplate",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的店铺配置",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pages",
                to="configurations.shopconfiguration",
            ),
        ),
        migrations.AlterField(
            model_name="pagetemplate",
            name="content",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="存储PageModule数组的JSON字段",
                validators=[pages.models.validate_json_content],
            ),
        ),
        migrations.AddIndex(
            model_name="pagetemplate",
            index=models.Index(
                fields=["shop", "device_type"], name="pages_paget_shop_id_334c5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pagetemplate",
            index=models.Index(
                fields=["shop", "-created_at"], name="pages_paget_shop_id_f073c5_idx"
            ),
        ),
    ]
