# Generated by Django 5.1.11 on 2025-10-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_migrate_pages_to_default_shop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagetemplate",
            name="target_area",
            field=models.CharField(
                blank=True,
                default="",
                help_text="关联乐天目标区域（兼容字段，逐步废弃）",
                max_length=100,
            ),
        ),
    ]
