# Generated by Django 5.1.11 on 2025-10-11 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_alter_target_area_allow_empty"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="pagetemplate",
            name="pages_paget_target__2926e2_idx",
        ),
        migrations.RemoveField(
            model_name="pagetemplate",
            name="target_area",
        ),
    ]
