# Generated by Django 5.1.11 on 2025-10-24 02:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_remove_target_area_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PageActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="活动记录的唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("page_id", models.UUIDField(db_index=True, help_text="关联的页面ID")),
                (
                    "page_name",
                    models.CharField(help_text="页面名称快照", max_length=255),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "创建"),
                            ("updated", "更新"),
                            ("deleted", "删除"),
                        ],
                        db_index=True,
                        help_text="操作类型",
                        max_length=20,
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(
                        blank=True, help_text="店铺名称快照", max_length=100
                    ),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, help_text="设备类型", max_length=20),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="活动发生时间"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="执行操作的用户",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "页面活动",
                "verbose_name_plural": "页面活动",
                "db_table": "page_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="page_activi_created_b6ca63_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="page_activi_user_id_9fc22b_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="page_activi_action_b80f25_idx",
                    ),
                ],
            },
        ),
    ]
