# Generated by Django 5.1.11 on 2025-07-01 05:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShopConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="唯一标识符",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shop_name",
                    models.CharField(help_text="用户可识别的店铺名称", max_length=100),
                ),
                (
                    "target_area",
                    models.CharField(
                        help_text="关联到PageTemplate的target_area字段，必须唯一",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "api_service_secret",
                    models.CharField(help_text="乐天API Service Secret", max_length=50),
                ),
                (
                    "api_license_key",
                    models.CharField(help_text="乐天API License Key", max_length=50),
                ),
                (
                    "ftp_host",
                    models.CharField(help_text="FTP服务器地址", max_length=255),
                ),
                (
                    "ftp_port",
                    models.IntegerField(default=21, help_text="FTP服务器端口"),
                ),
                ("ftp_user", models.CharField(help_text="FTP用户名", max_length=100)),
                ("ftp_password", models.CharField(help_text="FTP密码", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="最后更新时间"),
                ),
            ],
            options={
                "verbose_name": "店铺配置",
                "verbose_name_plural": "店铺配置",
                "db_table": "shop_configurations",
                "ordering": ["-created_at"],
            },
        ),
    ]
