# Generated by Django 5.1.11 on 2025-10-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopconfiguration",
            name="api_license_expiry_date",
            field=models.DateTimeField(
                blank=True, help_text="API许可证密钥到期日期", null=True
            ),
        ),
    ]
