# Generated by Django 5.1.11 on 2026-02-01 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurations", "0003_shopconfiguration_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopconfiguration",
            name="owner",
            field=models.ForeignKey(
                help_text="店铺配置的所有者",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop_configurations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
