name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # 前端代码检查和测试
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: TypeScript check
      run: pnpm tsc --noEmit
      
    - name: ESLint check
      run: pnpm lint
      
    - name: Prettier check
      run: pnpm format:check
      
    - name: Run tests with coverage
      run: pnpm test -- --coverage --reporter=verbose
      
    - name: Upload frontend coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: apps/frontend/coverage/
        
    - name: Check frontend coverage threshold
      run: |
        COVERAGE=$(pnpm test -- --coverage --reporter=json | jq '.coverageMap | to_entries | map(.value.summary) | map(.lines.pct) | add / length')
        echo "Frontend coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "❌ Frontend coverage ($COVERAGE%) is below 80% threshold"
          exit 1
        fi
        echo "✅ Frontend coverage ($COVERAGE%) meets 80% threshold"

  # 后端代码检查和测试
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend
        
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: pagemaker_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        cache-dependency-path: 'apps/backend/requirements.txt'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pytest-cov
        
    - name: Flake8 check
      run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
    - name: Black format check
      run: black --check .
      
    - name: Run tests with coverage
      env:
        DATABASE_URL: mysql://root:test_password@localhost:3306/pagemaker_test
        DJANGO_SETTINGS_MODULE: pagemaker.test_settings
      run: |
        python manage.py migrate --settings=pagemaker.test_settings
        coverage run --source='.' manage.py test --settings=pagemaker.test_settings
        coverage report --show-missing
        coverage html
        
    - name: Upload backend coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: backend-coverage
        path: apps/backend/htmlcov/
        
    - name: Check backend coverage threshold
      run: |
        COVERAGE=$(coverage report | grep TOTAL | awk '{print $4}' | sed 's/%//')
        echo "Backend coverage: $COVERAGE%"
        if (( $(echo "$COVERAGE < 80" | bc -l) )); then
          echo "❌ Backend coverage ($COVERAGE%) is below 80% threshold"
          exit 1
        fi
        echo "✅ Backend coverage ($COVERAGE%) meets 80% threshold"

  # 共享类型包测试
  shared-types:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/shared-types
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        cache-dependency-path: 'pnpm-lock.yaml'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      
    - name: TypeScript check
      run: pnpm tsc --noEmit
      
    - name: Run tests
      run: pnpm test 